version: '2'
services:
  tests:
    image: maven:3.3.9-jdk-8
    #container_name: maven-${JOB_NAME}-${BUILD_NUMBER}
    volumes:
     - ./provider:/data
     - ${HOME}/.m2:/root/.m2
    working_dir: /data
    command: mvn clean
    depends_on:
     - database
  status-checker:
    image: jwilder/dockerize
    command: echo ""
    depends_on:
     - database

  # Actual Environment
  database:
    image: mysql:5.6
    #container_name: mysql-${JOB_NAME}-${BUILD_NUMBER}
    volumes:
     - ./provider/src/test/resources/database:/docker-entrypoint-initdb.d/
    environment:
     MYSQL_ROOT_PASSWORD: 1234

#  docker-compose -f docker-compose-jenkins.yaml run --rm status-checker dockerize -wait tcp://database:3306 -timeout 20s